version: '3.6'

services:

  db:
    image: postgres:13
    container_name: "db"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: lunchtime
      POSTGRES_USER: lunchtime
      POSTGRES_DB: lunchtime

  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  bot:
    image: lunchtime:latest
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "bot"
    restart: always
    depends_on:
      - db

  #  worker:
  #    image: celery
  #    command: [ 'celery', 'worker', '-A', 'app.app', '-l', 'info' ]
  #    environment:
  #      - BROKER_URL=redis://:@localhost:6379/1
  ##      - RESULT_BACKEND=redis://redis:6379/0
  ##      - C_FORCE_ROOT=true
  #    volumes:
  #      - ./:/app/
  #    depends_on:
  #      - redis

volumes:
  postgres-db-volume: