"""Remove Connect

Revision ID: 7358625fcdba
Revises: c3c6ef8b7993
Create Date: 2021-11-11 00:18:02.572818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7358625fcdba'
down_revision = 'c3c6ef8b7993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('partner_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='connects_pkey'),
    sa.UniqueConstraint('partner_user_id', name='connects_partner_user_id_key'),
    sa.UniqueConstraint('user_id', name='connects_user_id_key')
    )
    # ### end Alembic commands ###
