"""Added back_populates

Revision ID: ab925a8c74e7
Revises: 7358625fcdba
Create Date: 2021-11-13 15:55:52.013550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab925a8c74e7'
down_revision = '7358625fcdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
